openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080/
  description: Generated server url
paths:
  /api/v1/userservice/user/{id}:
    get:
      tags:
      - user-controller
      operationId: getUserbyId
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: default response
          content:
            '*/*':
              schema:
                type: object
    put:
      tags:
      - user-controller
      operationId: updateUser
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: default response
          content:
            '*/*':
              schema:
                type: object
    delete:
      tags:
      - user-controller
      operationId: deleteUser
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: default response
          content:
            '*/*':
              schema:
                type: object
  /api/v1/userservice/user:
    get:
      tags:
      - user-controller
      operationId: getAllusers
      responses:
        '200':
          description: default response
          content:
            '*/*':
              schema:
                type: object
    post:
      tags:
      - user-controller
      operationId: registerUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: default response
          content:
            '*/*':
              schema:
                type: object
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int32
        firstname:
          type: string
        lastname:
          type: string
        school:
          type: string
        college:
          type: string